### ISSUE TITLE
下载下来了,但是报错了.(已 npm install   && npm start)

### ISSUE THREAD

**Issue by LukerSpringtree** [linkenliu/blog_express_angular#1]
先  npm install
然后  npm start

接着就报错了.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Invalid mongodb uri. Missing hostname

这个 我也 google了  没有找到解决的办法
evnets.js  估计也是 模块文件
我也不懂.

mongoDB我是打开了的 而且 我 Robomongo 是可以访问数据库的

哥  麻烦了 很想学习下你的源码.谢谢  麻烦了

**Comment by LukerSpringtree** [comment]
我知道了. 估计跟  redisDB有关系吧

我再看看 因为 resdis 我还没有 研究
我是新人一个  见谅

**Comment by linkenliu** [comment]
第一个错误明显是mongoDB报的，因为我源代码数据库是空的，所以你需要把它填充好。redis的话，你机器上装个吧。说不定以后你也会用到的。

**Comment by linkenliu** [comment]
@LukerSpringtree 第一个错误明显是mongoDB报的，因为我源代码数据库是空的，所以你需要把它填充好。redis的话，你机器上装个吧。说不定以后你也会用到的。

**Comment by LukerSpringtree** [comment]
行  "因为我源代码数据库是空的，所以你需要把它填充好。"
的意思是我需要在 MongoDB数据库里面加几条数据?
还是 修改一下 源码里面的 配置文件的  配置数据?

**Comment by linkenliu** [comment]
@LukerSpringtree 就是你需要把config/config.js/mongoDB的配置改成你自己的

**Comment by LukerSpringtree** [comment]
@linkenliu 
谢谢你
